repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [ --strict, --ignore-missing-imports, --allow-subclassing-any, --allow-any-generics]
        additional_dependencies: [types-all]

  - repo: local
    hooks:
      # update version on constants.py
      - id: version_updater
        name: version_updater
        entry: python3 ./src/version_updater.py
        language: python

      # For reformatting code
      - id: black
        name: black
        entry: black
        language: python
        types: [ python ]
        args: [ --line-length=88, --target-version=py311 ]

      # For upgrade python code syntax for newer versions of the language
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
        types: [ python ]

      # Tool for automatically reordering python imports
      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: python
        types: [ python ]

       # Removes unused imports and unused variables from Python code
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]

        # sort __all__ statements
      - id: sort-all
        name: Sort __all__ records
        description: Automatically Sort __all__ records alphabetically.
        entry: sort-all
        language: python
        types: [ python ]