# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-feedback
  namespace: tg-feedback-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-feedback
  template:
    metadata:
      labels:
        app: tg-feedback
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: tg-feedback
        image: bral1488/telegram-feedback-bot:main
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
          readOnly: true
        resources:
          limits:
            memory: "64Mi"
            cpu: "125m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
      volumes:
      - name: config-volume
        secret:
          secretName: tg-feedback-secret
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
